# Generated by Django 4.1.6 on 2023-02-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_general', '0003_delete_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('abbreviation', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_grade', models.CharField(max_length=20)),
                ('gpa_year_1', models.CharField(max_length=20)),
                ('thai', models.CharField(max_length=20)),
                ('math', models.CharField(max_length=20)),
                ('sci', models.CharField(max_length=20)),
                ('society', models.CharField(max_length=20)),
                ('hygiene', models.CharField(max_length=20)),
                ('art', models.CharField(max_length=20)),
                ('career', models.CharField(max_length=20)),
                ('langues', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general.branch')),
            ],
        ),
    ]
