# Generated by Django 4.1.6 on 2023-02-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='branch',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='app_general.branch'),
        ),
    ]
