# Generated by Django 4.1.6 on 2023-02-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0005_alter_data_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
