# Generated by Django 4.1.6 on 2023-03-17 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0019_alter_branch_abbreviation_alter_branch_name'),
        ('app_users', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว'), ('นาง', 'นาง'), ('อาจารย์', 'อาจารย์'), ('ผศ.', 'ผู้ช่วยศาสตราจารย์'), ('รศ.', 'รองศาสตราจารย์'), ('ศ.', 'ศาสตราจารย์')], max_length=50, null=True, verbose_name='คำนำหน้าชื่อ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_demo_model.branch', verbose_name='สาขาวิชา'),
        ),
    ]
