# Generated by Django 4.1.6 on 2023-03-17 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0019_alter_branch_abbreviation_alter_branch_name'),
        ('app_users', '0003_user_title_alter_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_demo_model.branch', verbose_name='สาขาวิชา'),
        ),
    ]
