# Generated by Django 4.1.6 on 2023-02-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0006_delete_appliedscimodelforperdiction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedscience',
            name='admission_grade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appliedscience',
            name='art',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appliedscience',
            name='career',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appliedscience',
            name='gpa_year_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appliedscience',
            name='hygiene',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appliedscience',
            name='langues',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appliedscience',
            name='math',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appliedscience',
            name='sci',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appliedscience',
            name='society',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appliedscience',
            name='thai',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthscience',
            name='admission_grade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthscience',
            name='art',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthscience',
            name='career',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthscience',
            name='gpa_year_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthscience',
            name='hygiene',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthscience',
            name='langues',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthscience',
            name='math',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthscience',
            name='sci',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthscience',
            name='society',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthscience',
            name='thai',
            field=models.CharField(max_length=50),
        ),
    ]
