# Generated by Django 4.1.6 on 2023-02-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0012_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='abbreviation',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
