# Generated by Django 4.1.6 on 2023-02-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0014_bio_chemi_dssi_ict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedScience',
        ),
        migrations.DeleteModel(
            name='HealthScience',
        ),
        migrations.DeleteModel(
            name='PureScience',
        ),
    ]
