# Generated by Django 4.1.6 on 2023-02-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0015_delete_appliedscience_delete_healthscience_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Major',
        ),
    ]
