# Generated by Django 4.1.6 on 2023-02-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0016_delete_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='major',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='chemi',
            old_name='major',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='dssi',
            old_name='major',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='ict',
            old_name='major',
            new_name='branch',
        ),
    ]
