# Generated by Django 4.1.6 on 2023-02-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0017_rename_major_bio_branch_rename_major_chemi_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('abbreviation', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_grade', models.CharField(max_length=20)),
                ('gpa_year_1', models.CharField(max_length=20)),
                ('thai', models.CharField(max_length=20)),
                ('math', models.CharField(max_length=20)),
                ('sci', models.CharField(max_length=20)),
                ('society', models.CharField(max_length=20)),
                ('hygiene', models.CharField(max_length=20)),
                ('art', models.CharField(max_length=20)),
                ('career', models.CharField(max_length=20)),
                ('langues', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='app_demo_model.branch')),
            ],
        ),
        migrations.DeleteModel(
            name='BIO',
        ),
        migrations.DeleteModel(
            name='CHEMI',
        ),
        migrations.DeleteModel(
            name='DSSI',
        ),
        migrations.DeleteModel(
            name='ICT',
        ),
    ]
