# Generated by Django 4.1.6 on 2023-02-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0018_branch_data_delete_bio_delete_chemi_delete_dssi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='abbreviation',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
