# Generated by Django 4.1.6 on 2023-03-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0019_alter_branch_abbreviation_alter_branch_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='langues',
            new_name='language',
        ),
    ]
