# Generated by Django 4.1.6 on 2023-03-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0020_rename_langues_data_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='TrainingData',
        ),
    ]
